import type { KnowledgeReference } from "../../domain/entities";

/** Referências que sustentam o catálogo mínimo — reutilizadas por entradas de currículo, conceitos e conexões via `referenceIds`. */
export const KNOWLEDGE_REFERENCES: KnowledgeReference[] = [
  {
    id: "ref-bncc-em",
    sourceType: "official_curriculum",
    title: "Base Nacional Comum Curricular — Ensino Médio",
    organization: "MEC",
    version: "2018",
    publicationDate: "2018-12-14",
    url: "http://basenacionalcomum.mec.gov.br/",
    documentId: null,
    section: "Ciências Humanas e Sociais Aplicadas",
    excerpt: "Compreender e analisar processos históricos e suas relações com o presente.",
    retrievedAt: "2026-01-01T00:00:00.000Z",
    confidence: 0.9,
    validationStatus: "validated",
  },
  {
    id: "ref-bncc-computacao",
    sourceType: "official_curriculum",
    title: "BNCC Computação — Complemento",
    organization: "MEC / CIEB",
    version: "2022",
    publicationDate: "2022-04-01",
    url: null,
    documentId: null,
    section: "Pensamento Computacional",
    excerpt: "Analisar impactos sociais, éticos e ambientais do uso de algoritmos e dados.",
    retrievedAt: "2026-01-01T00:00:00.000Z",
    confidence: 0.85,
    validationStatus: "validated",
  },
  {
    id: "ref-curriculo-paulista",
    sourceType: "official_curriculum",
    title: "Currículo Paulista — Ensino Médio",
    organization: "SEDUC-SP",
    version: "2021",
    publicationDate: "2021-03-01",
    url: null,
    documentId: null,
    section: "Itinerários Formativos",
    excerpt: "Articular saberes de diferentes componentes curriculares em torno de temas contemporâneos.",
    retrievedAt: "2026-01-01T00:00:00.000Z",
    confidence: 0.8,
    validationStatus: "validated",
  },
  {
    id: "ref-metodo-iah",
    sourceType: "iah_curated_connection",
    title: "Referencial do Método IAH — Eixos temáticos",
    organization: "IAH Educacional",
    version: "1.0",
    publicationDate: "2026-01-01",
    url: null,
    documentId: null,
    section: "Eixos de Inteligência Artificial & Humanidades",
    excerpt: "Eixos temáticos que conectam conteúdos curriculares a problemas contemporâneos de IA e sociedade.",
    retrievedAt: "2026-01-01T00:00:00.000Z",
    confidence: 0.95,
    validationStatus: "validated",
  },
  {
    id: "ref-conceitual-classicos",
    sourceType: "conceptual_reference",
    title: "Biblioteca conceitual interdisciplinar — referências clássicas",
    organization: "IAH Educacional",
    version: "1.0",
    publicationDate: null,
    url: null,
    documentId: null,
    section: "Conceitos e teorias associadas",
    excerpt: "Síntese curatorial de definições, autores e teorias associadas a conceitos interdisciplinares.",
    retrievedAt: "2026-01-01T00:00:00.000Z",
    confidence: 0.75,
    validationStatus: "in_review",
  },
];

export function getReferencesByIds(ids: string[]): KnowledgeReference[] {
  const set = new Set(ids);
  return KNOWLEDGE_REFERENCES.filter((reference) => set.has(reference.id));
}
